# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-31 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch_auth', '0002_auto_20170605_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBWhitelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.TextField(help_text='Nickname in whitelist', verbose_name='nickname')),
                ('user_id', models.TextField(help_text='USER ID in default db', verbose_name='user_id')),
                ('sub_twitch', models.TextField(help_text='User is subscriber?', verbose_name='sub_twitch')),
                ('in_whitelist', models.TextField(help_text='User in whitelist on server?', verbose_name='sub_twitch')),
            ],
        ),
    ]
