# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-31 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch_auth', '0003_dbwhitelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbwhitelist',
            name='old_nickname',
            field=models.TextField(default=None, help_text='OLD Nickname in whitelist', verbose_name='nickname'),
            preserve_default=False,
        ),
    ]
